### ISSUE TITLE
How do I use this in helix?

### ISSUE THREAD

**Issue by andrejohansson** [SilasMarvin/lsp-ai#25]
Hello,

I have installed lsp-ai

```powershell
❯ (Get-Command lsp-ai).Path
C:\Users\AndreJohansson\.cargo\bin\lsp-ai.exe
```

I have set my openai key

```
❯ $env:OPENAI_API_KEY
sk-proj-...
```

I have used [your example](https://github.com/SilasMarvin/lsp-ai/blob/main/examples/helix/openai-chat.toml) to configure my languages file. I added rust to it.

languages.toml
```toml
...
#################################
## Configuration for languages ##
#################################

[[language]]
name = "python"
language-servers = ["pyright", "lsp-ai"]

[[language]]
name = "rust"
auto-format = true
language-servers = ["rust-analyzer", "lsp-ai"]
```

Then I upen a rust file in helix
```powershell 
hx main.rs
```

How would I then trigger prompts and questions etc?
Please note: I'm a novice helix user, so any keyboard shortcuts and commands are helpful.
