### ISSUE TITLE
crash on helix

### ISSUE THREAD

**Issue by BastienVigneron** [SilasMarvin/lsp-ai#56]
Hello,

Thank you for your initiative.
I've tried to configure helix as mentioned in the examples directory with : 

```toml
[language-server.lsp-ai.config.models.model1]
  type = "llama_cpp"
  repository = "stabilityai/stable-code-3b"
  name = "stable-code-3b-Q5_K_M.gguf"
  n_ctx = 2048

[language-server.lsp-ai.config.completion]
  model = "model1"

[language-server.lsp-ai.config.completion.parameters]
  max_tokens = 32
  max_context = 1024

[language-server.lsp-ai.config.completion.parameters.fim]
  start = "<fim_prefix>"
  middle = "<fim_suffix>"
  end = "<fim_middle>"

```

When I try to use it, I get the following error: 

```
2024-08-08T19:46:48.116 helix_lsp::transport [ERROR] Exiting lsp-ai after unexpected error: Parse(Error("data did not match any variant of untagged enum ServerMessage", line: 0, column: 0))
2024-08-08T19:46:50.389 helix_lsp::transport [ERROR] lsp-ai err <- "ERROR lsp_ai::transformer_worker: sending response: \"SendError(..)\"\n"
```

Any idea ?
