### ISSUE TITLE
document helix + gemini

### ISSUE THREAD

**Issue by sigmaSd** [SilasMarvin/lsp-ai#90]
I tried helix + gemini with this project, here is where I landed
helix.toml
```toml
[language-server.lsp-ai]
command = "/home/mrcool/Downloads/lsp-ai-x86_64-unknown-linux-gnu"

[language-server.lsp-ai.config.memory]
file_store = { }

[language-server.lsp-ai.config.models.gemini2]
type = "gemini"
completions_endpoint = "https://generativelanguage.googleapis.com/v1beta/models/"
chat_endpoint = "https://generativelanguage.googleapis.com/v1beta/models/"
model = "gemini-2.0-flash-exp"
auth_token_env_var_name = "GOOGLE_API_KEY"

[language-server.lsp-ai.config.completion]
model = "gemini2"
parameters = {contents = [{role = "user", parts = [{text = "{CONTEXT} and {CODE}"}]}],  systemInstruction = {role = "system", parts = [{text = "You're giving the user input completion for code in his editor"}]}}
```

Almost works but the output needs some polishing

https://github.com/user-attachments/assets/d1e89500-ca34-4ad6-8468-a715fa88b0f9

Also its slow, maybe gemini is not suited for completion, is adding supermaven support possible ? since  its the fastest in completion 

Gemini/Supermaven/Copilot are free so maybe its a good idea to make using them more straight forward
